first_name = input("Введите ваше имя: ")
second_name = input("Введите вашу фамилию: ")
print( "Вас зовут " + first_name + " " + second_name )
First_name = input("Введите ваше имя: ")
Last_name = input("Введите вашу фамилию ")
print("Вас зовут: " + Last_name + " " + First_name)
